version: "3.7"

services:

  flask-api:
    container_name: flask-api
    ports:
      - 5000:5000
    image: oldcoyote03/tagger-api:v0.11
    depends_on:
      - roach
    command: sleep infinity

  roach:
    container_name: roach
    image: cockroachdb/cockroach:v22.1.6
    command: start-single-node --insecure
    ports:
      - 26257:26257
      - 8080:8080
